import React from 'react';

function TermsOfUse() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20">
      <h1 className="text-4xl font-orbitron font-bold mb-8">Terms of Use</h1>
      <div className="space-y-8 text-white/80">
        <div className="mb-6">
          <p className="text-sm text-white/60">Last Updated: 01/28/2025</p>
        </div>

        <p>
          Welcome to CYANIS, an AI-powered assistant designed to enhance your productivity and provide intelligent responses. By accessing and using CYANIS, you agree to comply with the following Terms of Use. If you do not agree, please refrain from using the service.
        </p>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
          <p>
            By using CYANIS, you acknowledge that you have read, understood, and agreed to these Terms of Use. These terms may be updated from time to time, and continued use constitutes acceptance of any changes.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">2. Use of the Service</h2>
          <p>
            CYANIS is provided for personal and professional assistance. Misuse of the platform, including harmful, illegal, or abusive activities, is strictly prohibited.
          </p>
          <p>
            You must be at least 16 years old to use this service.
          </p>
          <p>
            You are responsible for ensuring your access to CYANIS complies with all applicable laws.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">3. User Conduct</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Use CYANIS for illegal, harmful, or deceptive activities.</li>
            <li>Upload or transmit malicious software, spam, or harmful content.</li>
            <li>Attempt to reverse engineer, modify, or tamper with the AI model.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">4. Privacy and Data Usage</h2>
          <p>
            CYANIS respects user privacy. Data collected is handled in accordance with our Privacy Policy.
          </p>
          <p>
            We do not sell, distribute, or misuse personal data beyond the intended functionality of the service.
          </p>
          <p>
            You should avoid sharing sensitive, confidential, or personally identifiable information.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">5. Intellectual Property</h2>
          <p>
            All content generated by CYANIS remains the intellectual property of its respective users unless otherwise stated.
          </p>
          <p>
            CYANIS and its associated technologies are protected under copyright and intellectual property laws.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">6. Disclaimers and Limitations</h2>
          <p>
            CYANIS provides responses based on available data but does not guarantee accuracy, completeness, or reliability.
          </p>
          <p>
            The service is provided "as is," without warranties of any kind.
          </p>
          <p>
            We are not liable for any direct, indirect, or consequential damages resulting from the use of CYANIS.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">7. Termination of Use</h2>
          <p>
            We reserve the right to suspend or terminate access to CYANIS for any violation of these terms.
          </p>
          <p>
            Users may discontinue use at any time without prior notice.
          </p>
        </section>
      </div>
    </div>
  );
}

export default TermsOfUse;